// path: src/lib/renderer.ts
import type { Detail, Fact, PredicateView, RenderOptions } from "./types";
import { listRecentSourcesForEntity } from "./db";
import { getSource, countCorroborations } from "./db";
import { fullView } from "./query";

/**
 * In-memory cache for rendered Context.md.
 *
 * Why: baseline showed render() costs 50–470ms/call (WEG: 465ms p50) and the
 * agent loads 5 entities per query — that's 1–2s of pure render per ask, on
 * a corpus that doesn't change between asks. Caching brings warm hits to
 * ~0ms.
 *
 * Keyed by entity + detail + bitemporal coords. Bust on any insertFact for
 * that entity (see invalidateRenderCacheFor in db.ts).
 *
 * Bounded so a runaway entity-id doesn't blow memory; LRU is overkill for
 * a hackathon corpus of 133 entities — a Map with a soft cap behaves the
 * same in practice.
 */
const RENDER_CACHE = new Map<string, string>();
const RENDER_CACHE_SOFT_CAP = 256; // 133 entities × ~2 detail tiers in active use

function renderCacheKey(entity: string, opts: RenderOptions): string {
  const detail = opts.detail ?? 3;
  const av = opts.at_valid ?? "";
  const ak = opts.at_known ?? "";
  return `${entity}::${detail}::${av}::${ak}`;
}

export function invalidateRenderCacheForEntity(entity: string): void {
  // Match any cached key for this entity (across detail tiers / time coords).
  // Linear scan is fine at this size.
  const prefix = `${entity}::`;
  for (const k of RENDER_CACHE.keys()) {
    if (k.startsWith(prefix)) RENDER_CACHE.delete(k);
  }
}

export function clearRenderCache(): void {
  RENDER_CACHE.clear();
}

/**
 * Render the current bitemporal view of an entity as a Context.md document.
 *
 * Every fact line is wrapped in anchor comments so the patcher can do
 * surgical updates later (Buena track §2 — can't regenerate the whole file
 * without destroying human edits):
 *
 *   <!-- fact:IDENT -->
 *   rent.base         €1,500 / month  ^[lease-2024-03.pdf]
 *   <!-- /fact:IDENT -->
 *
 * IDENT is the fact's `ident` field (hash of entity+predicate+valid_from).
 * HTML comments are invisible to LLM readers and Markdown viewers.
 *
 * Invariants:
 *  - Sections appear in a deterministic order (cache-stable)
 *  - Keys within a section sorted by first-known-time
 *  - Conflicts render with a wrapping <!-- conflict:PRED --> block
 *  - Trailer line is always last, stable format
 */

const SECTION_ORDER = [
  { prefix: "identity.", heading: "Identity" },
  { prefix: "unit.", heading: "Unit details" },
  { prefix: "tenancy.", heading: "Tenancy" },
  { prefix: "ownership.", heading: "Ownership" },
  { prefix: "financial.", heading: "Financial" },
  { prefix: "incident.", heading: "Incidents & issues" },
  { prefix: "legal.", heading: "Legal" },
  { prefix: "maintenance.", heading: "Maintenance" },
  { prefix: "contract.", heading: "Contracts" },
  { prefix: "contacts.", heading: "Contacts" },
  { prefix: "condition.", heading: "Condition" },
  { prefix: "communication.", heading: "Communications" },
  { prefix: "insurance.", heading: "Insurance" },
  { prefix: "history.", heading: "History" },
  { prefix: "regulation.", heading: "Regulations" },
];

const KEY_PAD = 18;

export function render(entity: string, opts: RenderOptions = {}): string {
  const cacheKey = renderCacheKey(entity, opts);
  const hit = RENDER_CACHE.get(cacheKey);
  if (hit !== undefined) return hit;

  const out = renderUncached(entity, opts);

  if (RENDER_CACHE.size >= RENDER_CACHE_SOFT_CAP) {
    // Soft eviction: drop the first-inserted key. Map iteration order is
    // insertion order, so this is a cheap FIFO without LRU bookkeeping.
    const firstKey = RENDER_CACHE.keys().next().value;
    if (firstKey !== undefined) RENDER_CACHE.delete(firstKey);
  }
  RENDER_CACHE.set(cacheKey, out);
  return out;
}

function renderUncached(entity: string, opts: RenderOptions = {}): string {
  const detail: Detail = (opts.detail ?? 3) as Detail;
  // Detail tiers — drive what we include vs strip:
  //   1 = compact: no anchor comments, no Recent activity, no Conflicts math
  //                (still includes the conflict header + winning value),
  //                no Upcoming. Cheapest token spend for the agent's first-pass.
  //   2 = anchored: full anchored facts but no Recent activity
  //   3 = full: everything (default; what /context/[id] renders)
  const compact = detail <= 1;
  const noRecent = detail <= 2;
  const noUpcoming = detail <= 1;
  const { current: view, upcoming } = fullView(entity, {
    at_valid: opts.at_valid,
    at_known: opts.at_known,
  });

  const lines: string[] = [];
  const entityTitle = humanizeEntity(entity);
  const atValid = opts.at_valid ?? new Date().toISOString();
  const atKnown = opts.at_known ?? new Date().toISOString();

  lines.push(`# Context.md — ${entityTitle}`);
  lines.push(`> auto-generated by Hausbuch · entity:${entity}`);
  if (opts.at_valid || opts.at_known) {
    lines.push(`> bitemporal: at_valid=${atValid} · at_known=${atKnown}`);
  }
  lines.push("");

  // Bucket predicates into sections
  const buckets = new Map<string, Array<[string, PredicateView]>>();
  for (const s of SECTION_ORDER) buckets.set(s.heading, []);
  const other: Array<[string, PredicateView]> = [];

  for (const [key, val] of Object.entries(view)) {
    const sec = SECTION_ORDER.find((s) => key.startsWith(s.prefix));
    if (sec) buckets.get(sec.heading)!.push([key, val]);
    else other.push([key, val]);
  }

  const sortByKnown = (a: [string, PredicateView], b: [string, PredicateView]) => {
    const ak = firstFact(a[1]).known_from;
    const bk = firstFact(b[1]).known_from;
    return ak.localeCompare(bk);
  };

  const conflicts: Array<[string, PredicateView]> = [];

  for (const { heading } of SECTION_ORDER) {
    const rows = buckets.get(heading)!;
    if (rows.length === 0) continue;

    const singles = rows.filter(([, v]) => v.kind === "single").sort(sortByKnown);
    const blockConflicts = rows.filter(([, v]) => v.kind === "conflict");
    conflicts.push(...blockConflicts);

    if (singles.length === 0) continue;

    lines.push(`## ${heading}`);
    for (const [key, view] of singles) {
      if (view.kind !== "single") continue;
      lines.push(...factBlock(key, view.fact, detail, "", compact));
    }
    lines.push("");
  }

  if (other.length) {
    lines.push(`## Other`);
    for (const [key, v] of other.sort(sortByKnown)) {
      if (v.kind === "single") {
        lines.push(...factBlock(key, v.fact, detail, "", compact));
      } else {
        conflicts.push([key, v]);
      }
    }
    lines.push("");
  }

  if (!noUpcoming) {
    const upcomingEntries = Object.entries(upcoming);
    if (upcomingEntries.length > 0) {
      lines.push(`## Upcoming`);
      for (const [key, v] of upcomingEntries.sort(sortByKnown)) {
        if (v.kind === "single") {
          const when = v.fact.valid_from ? ` (eff. ${v.fact.valid_from})` : "";
          lines.push(...factBlock(key, v.fact, detail, when, compact));
        } else {
          lines.push(...conflictBlock(key, v, compact));
        }
      }
      lines.push("");
    }
  }

  if (conflicts.length > 0) {
    lines.push(`## ⚠ Conflicts`);
    for (const [key, v] of conflicts) {
      if (v.kind !== "conflict") continue;
      lines.push(...conflictBlock(key, v, compact));
      lines.push("");
    }
  }

  // Recent activity — last 5 sources ingested for this entity, newest first.
  // Surfaces sources even when extraction produced no facts (e.g., a lawyer
  // letter that didn't match an extractor pattern but is the most-recent event).
  const recent = noRecent ? [] : listRecentSourcesForEntity(entity, 5);
  if (recent.length > 0) {
    lines.push(`## Recent activity`);
    for (const s of recent) {
      const when = s.ingested_at.slice(0, 10);
      const kind = s.kind;
      const excerpt = s.raw_excerpt.replace(/\s+/g, " ").slice(0, 140);
      const ellipsis = s.raw_excerpt.length > 140 ? "…" : "";
      lines.push(`- ${when} · ${kind} · ${s.title}`);
      lines.push(`    "${excerpt}${ellipsis}"`);
    }
    lines.push("");
  }

  // Trailer (stable suffix)
  const allViews = [...Object.values(view), ...Object.values(upcoming)];
  const factCount = allViews.reduce(
    (n, v) => n + (v.kind === "single" ? 1 : v.facts.length),
    0,
  );
  const sourceCount = new Set(
    allViews.flatMap((v) =>
      v.kind === "single" ? [v.fact.source] : v.facts.map((f) => f.source),
    ),
  ).size;
  const conflictCount = allViews.filter((v) => v.kind === "conflict").length;

  lines.push(
    `<!-- Hausbuch · ${factCount} facts · ${sourceCount} sources · ${conflictCount} conflicts · detail=${detail} -->`,
  );

  return lines.join("\n");
}

/* ─────────────────────────────────────────────────────────────────────────
 * Anchored block renderers
 * ──────────────────────────────────────────────────────────────────────── */

function factBlock(
  predicate: string,
  fact: Fact,
  detail: Detail,
  suffix = "",
  compact = false,
): string[] {
  const line = renderFactLine(shortKey(predicate), fact, detail) + suffix;
  // Compact mode (detail≤1) drops the surgical-patch anchors. Anchors are
  // only useful when /api/patched-context is going to do an in-place edit —
  // for the agent's read path they're pure token overhead.
  if (compact) return [line];
  return [
    `<!-- fact:${fact.ident} -->`,
    line,
    `<!-- /fact:${fact.ident} -->`,
  ];
}

function conflictBlock(
  predicate: string,
  v: Extract<PredicateView, { kind: "conflict" }>,
  compact = false,
): string[] {
  const key = predicate.replace(/[^a-z0-9._-]/gi, "_");
  const block: string[] = [];
  if (!compact) block.push(`<!-- conflict:${key} -->`);
  if (compact) {
    // Compact: just the winning value with a "(conflict)" tag — agent
    // doesn't need to see the full posterior to answer "what's the rent?"
    const winner = v.posterior.entries.reduce((a, b) =>
      a.probability > b.probability ? a : b,
    );
    const winningFact = v.facts.find((f) => String(f.value) === String(winner.value)) ?? v.facts[0];
    const src = getSource(winningFact.source);
    block.push(
      `${shortKey(predicate).padEnd(Math.max(KEY_PAD, shortKey(predicate).length + 2), " ")}${formatValue(winningFact)} ⚠ conflict (P=${winner.probability.toFixed(2)})  ^[${src?.title ?? winningFact.source}]`,
    );
    return block;
  }
  block.push(`${shortKey(predicate)}:  ⚠ conflict`);
  for (const f of v.facts) {
    const src = getSource(f.source);
    const cite = src?.title ?? f.source;
    const when = f.valid_from ? ` (eff. ${f.valid_from})` : "";
    block.push(`  → ${formatValue(f)}${when}  ^[${cite}]`);
  }
  const poss = v.posterior.entries
    .map((e) => `P(${formatPosteriorValue(e.value, v.facts[0])})=${e.probability.toFixed(2)}`)
    .join(" · ");
  block.push(`  posterior: ${poss}`);
  block.push(`<!-- /conflict:${key} -->`);
  return block;
}

function renderFactLine(key: string, fact: Fact, detail: Detail): string {
  const src = getSource(fact.source);
  const cite = src?.title ?? fact.source;
  // KEY_PAD = 18 was a no-op for predicates whose short-key is already ≥18
  // chars (e.g. "gebaeudeversicherung" = 20) — the result was the key
  // concatenated directly to the value: "gebaeudeversicherung234.05".
  // Floor at key.length + 2 so we always get at least two spaces of
  // separation regardless of key length.
  const pad = key.padEnd(Math.max(KEY_PAD, key.length + 2), " ");
  const confMarker = detail >= 5 ? ` (c=${fact.confidence.toFixed(2)})` : "";

  // Multi-source corroboration: show how many distinct sources have asserted
  // this exact (entity, predicate, value) triple. When a single source asserts
  // the fact, the line stays unchanged. When several do, the user/agent can
  // see at a glance that the claim is independently corroborated.
  const corro = countCorroborations(fact.entity, fact.predicate, String(fact.value));
  if (corro.count > 1) {
    const others = corro.sources
      .filter((s) => s.id !== fact.source)
      .slice(0, 3)
      .map((s) => s.title)
      .join("; ");
    const tail = others
      ? `  ^[${cite}] · × ${corro.count} sources (also: ${others}${corro.count > 4 ? ", …" : ""})`
      : `  ^[${cite}] · × ${corro.count} sources`;
    return `${pad}${formatValue(fact)}${confMarker}${tail}`;
  }
  return `${pad}${formatValue(fact)}${confMarker}  ^[${cite}]`;
}

function formatValue(fact: Fact): string {
  if (fact.value === null || fact.value === undefined) return "null";
  if (fact.unit === "EUR/month") return `€${formatNumber(fact.value)} / month`;
  if (fact.unit === "USD/month") return `$${formatNumber(fact.value)} / month`;
  if (fact.unit === "GBP/month") return `£${formatNumber(fact.value)} / month`;
  if (fact.unit === "m²") return `${fact.value} m²`;
  if (typeof fact.value === "number") return formatNumber(fact.value);
  return String(fact.value);
}

function formatNumber(n: unknown): string {
  const num = typeof n === "number" ? n : Number(n);
  if (Number.isFinite(num)) return num.toLocaleString("en-US");
  return String(n);
}

function formatPosteriorValue(v: string, fact: Fact): string {
  if (fact.unit === "EUR/month") return `€${v}`;
  if (fact.unit === "USD/month") return `$${v}`;
  if (fact.unit === "GBP/month") return `£${v}`;
  return v;
}

function shortKey(predicate: string): string {
  const parts = predicate.split(".");
  if (parts.length === 1) return parts[0];
  return parts.slice(1).join(".");
}

function firstFact(v: PredicateView): Fact {
  return v.kind === "single" ? v.fact : v.facts[0];
}

function humanizeEntity(entity: string): string {
  if (entity === "property:berliner-str-42") return "Berliner Str. 42 · Mitte · Berlin";
  return entity.replace(/:/g, " · ").replace(/-/g, " ");
}
