// path: src/app/api/report/incident/[id]/route.ts
/**
 * Generate a Markdown report for an incident / recommendation thread.
 *
 *   GET /api/report/incident/{rec_id}            → text/markdown body
 *   GET /api/report/incident/{rec_id}?download=1 → attachment
 */

import { NextRequest, NextResponse } from "next/server";
import { db } from "@/lib/db";
import { getRecommendations } from "@/lib/recommendations";
import { listActions } from "@/lib/actions";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

export async function GET(
  req: NextRequest,
  ctx: { params: Promise<{ id: string }> },
) {
  db();
  const { id } = await ctx.params;
  const recId = decodeURIComponent(id);
  const recs = getRecommendations();
  const rec = recs.find((r) => r.id === recId);
  if (!rec) {
    return NextResponse.json({ error: "recommendation not found" }, { status: 404 });
  }

  // Pull related audit steps for the entity
  const audit = listActions({ entity: rec.entity_id, limit: 60 });

  const lines: string[] = [];
  lines.push(`# Incident report — ${rec.title_en ?? rec.title}`);
  lines.push("");
  lines.push(`> Generated by Hausbuch · ${new Date().toISOString()}`);
  lines.push("");

  lines.push(`## Overview`);
  lines.push("");
  lines.push(`- **Severity:** ${rec.severity}`);
  lines.push(`- **Entity:** ${rec.entity_name} (\`${rec.entity_id}\`)`);
  lines.push(`- **Category:** ${rec.category}`);
  lines.push(`- **Opened:** ${rec.created_at.slice(0, 10)}`);
  if (rec.entity_reputation) {
    lines.push(
      `- **Reputation at write-time:** ${rec.entity_reputation.score.toFixed(2)} · ${rec.entity_reputation.band}` +
        ` · ${rec.entity_reputation.incidents_open} open · ${rec.entity_reputation.mahnung_count} dunning`,
    );
  }
  lines.push("");
  lines.push(rec.summary_en ?? rec.summary);
  lines.push("");

  if (rec.email_chain && rec.email_chain.length > 0) {
    lines.push(`## Email thread (${rec.email_chain.length} messages)`);
    lines.push("");
    for (const e of [...rec.email_chain].sort((a, b) =>
      a.date.localeCompare(b.date),
    )) {
      lines.push(`### ${e.date.slice(0, 16).replace("T", " ")} · ${e.from ?? "—"}`);
      lines.push(`**${e.title}**`);
      if (e.excerpt) {
        lines.push("");
        lines.push("> " + e.excerpt.replace(/\n/g, "\n> "));
      }
      lines.push("");
    }
  }

  if (rec.facts && rec.facts.length > 0) {
    lines.push(`## Bitemporal facts on file`);
    lines.push("");
    lines.push(`| Predicate | Value | Known from | Source |`);
    lines.push(`|---|---|---|---|`);
    for (const f of [...rec.facts].sort((a, b) =>
      b.known_from.localeCompare(a.known_from),
    )) {
      lines.push(
        `| \`${f.predicate}\` | ${escapeMd(f.value)} | ${f.known_from.slice(0, 10)} | ${escapeMd(f.source_title)} |`,
      );
    }
    lines.push("");
  }

  if (audit.length > 0) {
    lines.push(`## System actions (last ${audit.length})`);
    lines.push("");
    lines.push(`| Time | Actor | Action | Latency | Partner |`);
    lines.push(`|---|---|---|---|---|`);
    for (const a of audit.slice(0, 30)) {
      lines.push(
        `| ${a.ts.slice(0, 19).replace("T", " ")} | ${a.actor} | \`${a.action}\` | ${a.latency_ms ?? "—"}ms | ${a.partner ?? "—"} |`,
      );
    }
    lines.push("");
  }

  if (rec.actions && rec.actions.length > 0) {
    lines.push(`## Recommended next actions`);
    lines.push("");
    for (const a of rec.actions) {
      lines.push(`- **${a.label}** (${a.type})`);
      if (a.recipient) lines.push(`  - to: ${a.recipient.name} <${a.recipient.email ?? "—"}>`);
      if (a.reputation) {
        lines.push(
          `  - reputation: ${a.reputation.score.toFixed(2)} · ${a.reputation.band}` +
            (a.reputation.avoided
              ? ` · routed around ${a.reputation.avoided.name} (${a.reputation.avoided.score.toFixed(2)})`
              : ""),
        );
      }
    }
    lines.push("");
  }

  lines.push(`---`);
  lines.push(`_Hausbuch · property management context engine. Every fact in this report is bitemporal and source-cited._`);

  const md = lines.join("\n");
  const download = req.nextUrl.searchParams.get("download");
  const headers: Record<string, string> = {
    "Content-Type": "text/markdown; charset=utf-8",
  };
  if (download) {
    const safeId = recId.replace(/[^a-z0-9_-]+/gi, "_");
    headers["Content-Disposition"] = `attachment; filename="incident-${safeId}.md"`;
  }
  return new NextResponse(md, { headers });
}

function escapeMd(v: unknown): string {
  return String(v).replace(/\|/g, "\\|").replace(/\n/g, " ").slice(0, 200);
}
