// path: scripts/test-patcher.ts
// path: scripts/test-patcher.ts
import { patch, factAnchors } from "../src/lib/patcher";

const before = `# Context.md — Berliner Str. 42 · Mitte · Berlin
> auto-generated by Lumen · entity:property:berliner-str-42

## Identity
<!-- fact:abc123 -->
address           Berliner Str. 42, 10178 Berlin  ^[land-registry.pdf]
<!-- /fact:abc123 -->
<!-- fact:def456 -->
owner             Müller Immobilien GmbH  ^[land-registry.pdf]
<!-- /fact:def456 -->

## Human notes

> IMPORTANT: The previous property manager (Herr Weber, retired 2024)
> mentioned the basement floods in heavy rain. Lumen shouldn't touch
> this section — it's not in any source document but we know it's true.

## Condition
<!-- fact:xyz789 -->
last_inspection   2026-02-14  ^[slack:#maint msg-8831]
<!-- /fact:xyz789 -->

<!-- Lumen · 3 facts · 2 sources · 0 conflicts · detail=3 -->
`;

// Simulate: owner has been updated (new source, same predicate).
const ops = [
  {
    kind: "upsert-fact" as const,
    ident: "def456",
    block: ["owner             Müller Real Estate Holdings  ^[contract-2027.pdf]"],
  },
];

const result = patch(before, ops);

console.log("========== BEFORE ==========");
console.log(before);
console.log("========== AFTER ==========");
console.log(result.next);
console.log("========== DIFF REPORT ==========");
console.log(`  applied: ${result.applied}`);
console.log(`  skipped: ${result.skipped.length}`);
console.log(`  human lines preserved: ${result.preserved_user_lines}`);
console.log();
if (result.next.includes("IMPORTANT: The previous property manager")) {
  console.log("✓ HUMAN EDIT PRESERVED");
} else {
  console.log("✗ HUMAN EDIT LOST — this is a bug");
  process.exit(1);
}
if (result.next.includes("Müller Real Estate Holdings")) {
  console.log("✓ MACHINE UPDATE APPLIED");
} else {
  console.log("✗ MACHINE UPDATE MISSING — this is a bug");
  process.exit(1);
}
if (result.next.includes("last_inspection")) {
  console.log("✓ UNTOUCHED BLOCKS UNCHANGED");
} else {
  console.log("✗ UNRELATED BLOCK DAMAGED — this is a bug");
  process.exit(1);
}
